### ISSUE TITLE
About domain overlap in the dataset

### ISSUE THREAD

**Issue by Monstarrr** [siat-nlp/GALAXY#5]
Hello!
I found that dataset Multiwoz has already been included in your pretrained data UniDA, while it is also used as your fine-tuning data. Will there be unfairness in your low-resource experiment result?
Thanks for your response in advance!

**Comment by HwwAncient** [comment]
Thank you for your interest.
First, UniDA only contains the training dataset of MultiWOZ. Second, for each X% low-resource setting experiment, we re-train a GALAXY model on our pre-training data only including the X% MultiWOZ training dataset.
